### ISSUE TITLE
Bad address error

### ISSUE THREAD

**Issue by CustomCheat** [Trayzik/TrayzWare#1]
After I actually managed to launch the jar (i had to search pretty far to actually find how to) it did launch, but unfortunately it errored out:
```
[customcheat@customcheat Downloads]$ sudo java -jar --module-path $PATH_TO_FX --add-modules javafx.controls TrayzWare.jar
Loading TrayzWare...
Loaded 152 netvars, 55 offsets!
com.sun.jna.LastErrorException: [14] Bad address
	at com.github.jonatino.natives.unix.unix.process_vm_readv(Native Method)
	at com.github.jonatino.process.impl.unix.UnixProcess.read(UnixProcess.java:88)
	at com.github.jonatino.process.DataSource.read(DataSource.java:74)
	at com.github.jonatino.process.DataSource.readInt(DataSource.java:48)
	at pl.trayz.cheats.objects.memory.Pointer.readInt(Pointer.java:34)
	at pl.trayz.cheats.TrayzWare.getGameState(TrayzWare.java:127)
	at pl.trayz.cheats.TrayzWare.<init>(TrayzWare.java:108)
	at pl.trayz.cheats.TrayzWare.main(TrayzWare.java:141)
[customcheat@customcheat Downloads]$ 
```
Can you somehow fix this? Seems like some address did not get updated correctly or something. Anyways, happy to see someone developing cheats for linux too!

**Comment by yoczus** [comment]
what version and distro of linux do you have exactly? @CustomCheat

**Comment by CustomCheat** [comment]
Arch, don't really know what kernel version, but I would guess pretty recent. I would have to get on my computer to know the exact version, so if you really need to know the exact, i will tell you tomorrow.
